### PR TITLE
adding Weill week 3 files

### PR DESCRIPTION
**Pull request by alweill**

### CODE REVIEW

**Comment by lwasser** [comment]
hey @alweill this is a good start but you are missing the knitr output which should be an `.html` document. were you able to knit?

**Comment by alweill** [comment]
Thought I had added both files but I must have forgotten to add the html file. I've added it now. I was able to knit, but for some reason I got an error that the raster files did not exist when I knit it, even though they loaded fine when run in the console. I couldn't figure out how to fix this.

**Comment by lwasser** [comment]
Thank you @alweill !!

**Comment by lwasser** [comment]
Hey Allie - I see this. The structure of your html file is also different than I've seen with the default output from knitr. We can look at it tomorrow.

Leah
--
Leah A. Wasser, Ph.D.
Supervising Scientist
Education / Data Products
National Ecological Observatory Network (NEON)
Boulder, Colorado
--------------------
For free tutorials and resources on working with spatio-temporal data:
http://www.neondataskills.org<http://www.neondataskills.org/>

**Comment by alweill** [comment]
Yes--I also noticed that my Rmd file didn't generate the default heading
when I opened a new Rmd file as the tutorial indicated. Maybe it's the
version of R-studio? I downloaded my current version only a few months back
so I didn't bother to update it, but I could try that.

**Comment by lwasser** [comment]
HI Allie!
No worries. Please do update Rstudio. It's important to have all of the current versions of R, Rstudio and the associated packages.
I'm not 100% convinced that is the issue however with your html file, however. Let's have a look tomorrow :) Are you knitting using the "knit" button in R studio OR are you knitting from the command line? I ask because when you knit from the command line, you run into path issues UNLESS the rmd file is in the same working dir as your data. That could be an issue with the errors but there still is some other format issues that seem odd to me!

Leah

**Pull request merged**
