### PR TITLE
RR

### PR DESCRIPTION
**Pull request by richyrich00**
test

### CODE REVIEW

**Comment by lwasser** [comment]
Hey @richyrich00 ! 

Thank you for your week 2 git submission! A few notes about git (please ignore this first part if you already are a git wiz).

1. Notice that I am leaving you feedback on your pull request! You can respond to this feedback on git. But you can also simply reply to this email to respond. This is a great way for you to suggest changes to my (NEON’s) repo, and for me to give you feedback and communicate with you on those suggest changes.
2. Also notice that when I leave feedback, i can tag you by writing @ and your git username.
3. Finally - I can leave you feedback using MARKDOWN syntax to format the message. Git will render it for me.
4. If I wanted to, I could look at your file and leave you feedback on any line or lines in the file. This is very useful if you are working with someone else on code / text changes to documents in a git repo.

**Next steps - please respond to this comment so I can see you have received it! When you do, i’ll merge your pull request into the NEON central repo!**

Now on to your research project - here’s some more specific feedback:

It is so interesting that you are looking to fuse natural and social sciences in your research! Your topic looks great - you may want to consider that all of the data that you are interested in - is not yet available through NEON. We do have vegetation indices (greenness, etc) but no vegetation composition, species level products or landcover data. So, you while you're you may want to think about focusing on a particular part of remote sensing that you'd like to better understand. And work on that. For instance, you could work on some general classification of landcover types at a site using the R caret library. Or you could compare vegetation greenness with other metrics at several sites. 

Looking forward to chatting more in 1+ weeks!
Leah

**Comment by richyrich00** [comment]
Hi Leah,

Sorry for the delay! I've been on travel for the last several days. I'm at the Bay Area for a conference this week so I'm finally getting around to some down time. I appreciate the intel and I'll make some revisions and tighten my scope based on the available data. Appreciate it!

**Comment by richyrich00** [comment]
I hope it worked this time!

**Comment by richyrich00** [comment]
OK- I think I finally got it right-ish(?)

**Comment by lwasser** [comment]
looks like you got it @richyrich00 !! thank you!

**Pull request merged**
