### PR TITLE
Week 2 and 3 assignments

### PR DESCRIPTION
**Pull request by MPVeldhuis**
Sync the Bio and Capstone project to the Central Repository

### CODE REVIEW

**Comment by lwasser** [comment]
Hi @MPVeldhuis 
Great effort submitting your PR to git! It looks like this is your first time using git (atleast with this account). Is that the case?

Looking at your file, it appears as if you submitted a file in `.docx` format which is microsoft word. For this exercise, it's required that you submit the file in .md format. We'd suggest that rather than working in word, that you work in a text editor like notepad, or a atom.io (my preferred editor these days). This way you'll avoid any of the software specific extentions / formats when you save. 

Your next steps.

1. Please RESAVE your file in .md format. We recommend doing this by opening it up in a text editor like atom.io and saving it there.
2. at the command line, AFTER you've resaved as a .md file, delete the docx file using the command: 

.

So - thank you for your week 2 git submission! A few notes about git (please ignore this first part if you already are a git wiz).

1. Notice that I am leaving you feedback on your pull request! You can respond to this feedback on git. But you can also simply reply to this email to respond. This is a great way for you to suggest changes to my (NEON’s) repo, and for me to give you feedback and communicate with you on those suggest changes. 
2. Also notice that when I leave feedback, i can tag you by writing `@` and your git username.
3. Finally - I can leave you feedback using MARKDOWN syntax to format the message. Git will render it for me.
4. If I wanted to, I could look at your file and leave you feedback on any line or lines in the file. This is very useful if you are working with someone else on code / text changes to documents in a git repo. 

**Next steps - please respond to this comment so I can see you have received it! When you do, i’ll merge your pull request into the NEON central repo!**

Now on to your research project - here’s some more specific feedback:

**Comment by MPVeldhuis** [comment]
Dear Leah,

Thanks for your feedback. I saved the file again as a .md file and removed
the .docx file as suggested.

I'm sorry to only get back to you now, but I've been doing fieldwork in
remote parts of Africa in the last two weeks. I actually uploaded week 2
assignment while waiting at the airport just before boarding. I hope the
assignment of week 2 is alright now.

I'll get started with week three now.

Cheers,
Michiel

----------------------------------------------------------------------------------------------------
MSc Michiel Veldhuis
Postdoc Ecosystem Ecology
AfricanBioServices (africanbioservices.eu)

Conservation Ecology Group
Groningen Institute for Evolutionary Life Sciences (GELIFES)
University of Groningen
The Netherlands

**Comment by lwasser** [comment]
hey @MPVeldhuis no problem. You'll have to resubmit your pull request for the changes to be available in this pull request. please let us know if you have questions

**Comment by MPVeldhuis** [comment]
Hi Leah,

I think the files are updated now and changes are available in this pull request for you to merge. Can you let me know if this is alright now or whether you can't see the changes made?

Michiel

**Comment by lwasser** [comment]
hey @MPVeldhuis i'm going to merge this but you still have a .docx file in the PR! remind us to show you how to remove that from your repo on Monday.

**Pull request merged**
