### PR TITLE
Updating Fork

### PR DESCRIPTION
**Pull request by dramccaffrey**

### CODE REVIEW

**Comment by lwasser** [comment]
Hey @dramccaffrey ! 

Thank you for your week 2 git submission! A few notes about git (please ignore this first part if you already are a git wiz).

1. Notice that I am leaving you feedback on your pull request! You can respond to this feedback on git. But you can also simply reply to this email to respond. This is a great way for you to suggest changes to my (NEON’s) repo, and for me to give you feedback and communicate with you on those suggest changes.
2. Also notice that when I leave feedback, i can tag you by writing @ and your git username.
3. Finally - I can leave you feedback using MARKDOWN syntax to format the message. Git will render it for me.
4. If I wanted to, I could look at your file and leave you feedback on any line or lines in the file. This is very useful if you are working with someone else on code / text changes to documents in a git repo.
5. When you use headings in markdown, be sure to add a **SPACE** after the `#` so heading one would look like this: `# Heading One` rather than this `#Heading One`. Not using the space works sometimes, but some markdown renderers (including jekyll in github.com which i'll mention during the institute) won't render a heading without a space properly. 

**Next steps - please respond to this comment so I can see you have received it! When you do, i’ll merge your pull request into the NEON central repo!**

Now on to your research project - here’s some more specific feedback:

You are correct - we don't have a lot of organismal data yet available. However, you could explore what we have a bit and work on method development while you are here. You may also enjoy working with the hyperspectral data and experimenting with classification. Have you used the caret package yet? it may be useful to you.

Looking forward to chatting more in 1+ weeks!
Leah

**Comment by dramccaffrey** [comment]
Greetings,

Apologies for the short delay! Yes, I have successfully received the pull
request. Very interesting that we can reply directly by email.

Looking forward to next week!
-Dave

David McCaffrey

M.Sc. Candidate

ARTeMiS Lab - University of Lethbridge

p: 403-894-4494

e: david.mccaffrey@uleth.ca

**Comment by lwasser** [comment]
thanks @dramccaffrey see you next week!

**Comment by lwasser** [comment]
hey @dramccaffrey - i did not take a close enough look at your pull request. Your bio is actually in the MAIN DIRECTORY of the git repo rather than the week 2 or week 3 directory. Here's how you fix this. 

In your git repo folder on your computer - be sure to MOVE your bio file yourname.md to the correct folder. In this case - `pre-institute2-git`. Now you can go to the command line and do a git status. git add the file in the new folder 

git add /pre-institute2-git/yourname.md 

Then git rm the folder in the main directory.

Commit this change and then submit another pull request. you can do this with your week 3 assignment if you'd like. please get in touch with any questions

**Comment by dramccaffrey** [comment]
Greetings,

Hopefully I got it right this time. I moved McCaffrey-David.md into the
pre-institue2-git folder, added using 'git add', and committed this change
using 'git push origin gh-pages'. Prior to making a pull request to commit
this change, I started with a pull request using base:me head:neon to make
sure I hadn't missed any updates over the past few days. I then made a pull
request to add my commit to the neon repo using base:neon head:me.

Was this correct?

Thanks for the tips - Week 3 assignment coming up soon! The pre-institute
work has been insightful. Looking forward to next week.

Cheers,
-Dave



David McCaffrey

M.Sc. Candidate

ARTeMiS Lab - University of Lethbridge

p: 403-894-4494

e: david.mccaffrey@uleth.ca

**Pull request merged**
