### PR TITLE
Gh pages

### PR DESCRIPTION
**Pull request by cassondrawalker**

### CODE REVIEW

**Comment by lwasser** [comment]
hey @cassondrawalker !

Thank you for your week 2 git submission! A few notes about git (please ignore this first part if you already are a git wiz which i'm fairly certain you are).

1. Notice that I am leaving you feedback on your pull request! You can respond to this feedback on git. But you can also simply reply to this email to respond. This is a great way for you to suggest changes to my (NEON’s) repo, and for me to give you feedback and communicate with you on those suggest changes.
2. Also notice that when I leave feedback, i can tag you by writing @ and your git username.
3. Finally - I can leave you feedback using MARKDOWN syntax to format the message. Git will render it for me.
4. If I wanted to, I could look at your file and leave you feedback on any line or lines in the file. This is very useful if you are working with someone else on code / text changes to documents in a git repo.

One Note: your commit message says "gh-pages". For your next submission, please consider a more descriptive message like "C Walker bio / project markdown file added". Or something like that. 

Next steps - please respond to this comment so I can see you have received it! When you do, i’ll merge your pull request into the NEON central repo!

Now on to your research project - here’s some more specific feedback:
Scaling between terrestrial and airborne lidar data sounds like a very interesting project! Particularly with the challenges surrounding geolocation in terrestrial relative to airborne! While we don't currently have terrestrial lidar, some other labs have been collecting it at NEON sites and may be willing to share with you. Also, we have an LAI data product. You can chat with the scientist who is developing it while you're here!

Looking forward to chatting more in 1+ weeks!
Leah

**Comment by cassondrawalker** [comment]
I saw that the request said gh-pages, and I didn't relaize that I could
change the subject line....sorry about that.  Thank you for the feed back!!

Cassondra

**Comment by lwasser** [comment]
@cassondrawalker  you got it. thank you Cassondra! :)

**Comment by cassondrawalker** [comment]
Thanks!!  Sorry about the confusion.

**Comment by lwasser** [comment]
No confusion, cassondra :) great work getting this submitted!
See you soon.
Leah

**Pull request merged**
